---
version: '3'
services:
  umami:
    image: umami:dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@umami_db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - umami_db
    restart: always
  umami_db:
    image: postgres:13
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
volumes:
  umami-db-data:
